#!/bin/sh

# Welcome to the thoughtbot laptop script!
# Be prepared to turn your laptop (or desktop, no haters here)
# into an awesome development machine.

brew bundle --file=- <<EOF
brew "antigen"
brew "thefuck"
EOF

fancy_echo "Install Apple Store applications..."
mas install 748212890 # Memory Cleaner
mas install 497799835 # Xcode
mas install 443987910 # 1Password
mas install 451444120 # Memory Clean
mas install 525742250 # JPEGmini Lite
mas install 1091189122 # Bear

mas upgrade

fancy_echo "Ruby setup..."
gem update --system
gem_install_or_update "bundler"
number_of_cores=$(sysctl -n hw.ncpu)
bundle config --global jobs $((number_of_cores - 1))
gem_install_or_update "overcommit"
